name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'travel-planner/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./travel-planner
        run: npm ci
        
      - name: Run ESLint
        working-directory: ./travel-planner
        run: npm run lint
        continue-on-error: true
        
      - name: Build Next.js app
        working-directory: ./travel-planner
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          
      - name: Check build artifacts
        working-directory: ./travel-planner
        run: |
          if [ -d ".next" ]; then
            echo "✅ Build successful"
          else
            echo "❌ Build failed"
            exit 1
          fi

  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'travel-planner/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./travel-planner
        run: npm ci
        
      - name: Run TypeScript compiler
        working-directory: ./travel-planner
        run: npx tsc --noEmit

